<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>SnipPlus.App</RootNamespace>
    <AssemblyName>SnipPlus.App</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsPackageType>MSIX</WindowsPackageType>
    <WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
    <AppxPackageSigningEnabled>false</AppxPackageSigningEnabled>
    <GenerateAppInstallerFile>false</GenerateAppInstallerFile>
    <AppxAutoIncrementPackageRevision>false</AppxAutoIncrementPackageRevision>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="Microsoft.Graphics.Win2D" />
    <ProjectReference Include="..\SnipPlus.Contracts\SnipPlus.Contracts.csproj" />
    <ProjectReference Include="..\SnipPlus.Core\SnipPlus.Core.csproj" />
    <ProjectReference Include="..\SnipPlus.Windows\SnipPlus.Windows.csproj" />
  </ItemGroup>
</Project>
